name: letterboxd
channels:
dependencies:
  - python=3.11
  - pip
  - psycopg           # ← psycopg v3 from conda-forge (prebuilt)
  - libpq             # optional but nice to pin the client lib explicitly
  - ca-certificates   # good hygiene in containers
  - pip:
      - aiohttp
      - beautifulsoup4
      - lxml
      - pandas
      - openpyxl
      - scikit-surprise
      # (keep any other pip-only deps here)
